### ISSUE TITLE
Moving answer/question portions on polls and surveys refreshes page w/out saving modification.

### ISSUE THREAD

**Issue by itsbenweeks** [mckinseyacademy/xblock-poll#15]
When authoring a poll or survey it is impossible to modify the order of the answers questions without deleting and reauthoring answers. Using the move up or move down arrows causes the page to refresh, and any unsaved progress is lost.

Steps to Reproduce:
1. Enable poll and/or survey from advanced settings. 
2. Create a new poll or survey component. 
3. Try to move any existing answer or question up or down.

**Comment by antoviaque** [comment]
@itsbenweeks Thanks again for the bug report. This should have been addressed by https://github.com/open-craft/xblock-poll/issues/5 . Can you test and let me and @e-kolpakov if that fixes your issue?

In the meantime I will close that issue since it's merged, but don't hesitate to reopen if you still have issues with this.
